/**
 * Quizzes that have a cover of their own on disk.
 *
 * GENERATED - do not edit. `scripts/generate-quiz-covers.mts` rewrites this
 * from `docs/quiz-image-prompts/manifest.json` every time it draws the covers,
 * so the list can never claim a file that was never rendered.
 *
 * WHY IT EXISTS
 *
 * A cover only reached a quiz if the database happened to hold an `imageUrl`
 * for it, which meant every quiz added after the last run of
 * `assign-quiz-images.mts` fell through to its category picture - forty-two
 * Jesaja and Klaagliederen quizzes all wearing the same cover. Matching on the
 * slug instead makes the artwork on disk the answer, so drawing a cover is the
 * only step: no migration, and a new quiz is right the moment its file exists.
 */

const SLUGS = [
  'algemene-bijbelkennis',
  'algemene-bijbelkennis-deel-1',
  'daniel-bijbelquiz-deel-1',
  'daniel-bijbelquiz-deel-10',
  'daniel-bijbelquiz-deel-11',
  'daniel-bijbelquiz-deel-12',
  'daniel-bijbelquiz-deel-2',
  'daniel-bijbelquiz-deel-3',
  'daniel-bijbelquiz-deel-4',
  'daniel-bijbelquiz-deel-5',
  'daniel-bijbelquiz-deel-6',
  'daniel-bijbelquiz-deel-7',
  'daniel-bijbelquiz-deel-8',
  'daniel-bijbelquiz-deel-9',
  'diepere-bijbelstudie',
  'ester-bijbelquiz-deel-1',
  'ester-bijbelquiz-deel-10',
  'ester-bijbelquiz-deel-2',
  'ester-bijbelquiz-deel-3',
  'ester-bijbelquiz-deel-4',
  'ester-bijbelquiz-deel-5',
  'ester-bijbelquiz-deel-6',
  'ester-bijbelquiz-deel-7',
  'ester-bijbelquiz-deel-8',
  'ester-bijbelquiz-deel-9',
  'exodus-bijbelquiz-deel-1',
  'exodus-bijbelquiz-deel-10',
  'exodus-bijbelquiz-deel-2',
  'exodus-bijbelquiz-deel-3',
  'exodus-bijbelquiz-deel-4',
  'exodus-bijbelquiz-deel-5',
  'exodus-bijbelquiz-deel-6',
  'exodus-bijbelquiz-deel-7',
  'exodus-bijbelquiz-deel-8',
  'exodus-bijbelquiz-deel-9',
  'genesis',
  'habakuk-bijbelquiz-deel-1',
  'habakuk-bijbelquiz-deel-2',
  'habakuk-bijbelquiz-deel-3',
  'handelingen-bijbelquiz-deel-1',
  'handelingen-bijbelquiz-deel-10',
  'handelingen-bijbelquiz-deel-11',
  'handelingen-bijbelquiz-deel-12',
  'handelingen-bijbelquiz-deel-13',
  'handelingen-bijbelquiz-deel-14',
  'handelingen-bijbelquiz-deel-15',
  'handelingen-bijbelquiz-deel-16',
  'handelingen-bijbelquiz-deel-17',
  'handelingen-bijbelquiz-deel-18',
  'handelingen-bijbelquiz-deel-19',
  'handelingen-bijbelquiz-deel-2',
  'handelingen-bijbelquiz-deel-20',
  'handelingen-bijbelquiz-deel-21',
  'handelingen-bijbelquiz-deel-22',
  'handelingen-bijbelquiz-deel-23',
  'handelingen-bijbelquiz-deel-24',
  'handelingen-bijbelquiz-deel-25',
  'handelingen-bijbelquiz-deel-26',
  'handelingen-bijbelquiz-deel-27',
  'handelingen-bijbelquiz-deel-28',
  'handelingen-bijbelquiz-deel-3',
  'handelingen-bijbelquiz-deel-4',
  'handelingen-bijbelquiz-deel-5',
  'handelingen-bijbelquiz-deel-6',
  'handelingen-bijbelquiz-deel-7',
  'handelingen-bijbelquiz-deel-8',
  'handelingen-bijbelquiz-deel-9',
  'helden-en-martelaren',
  'het-boek-spreuken',
  'hooglied',
  'hooglied-deel-1',
  'hooglied-deel-2',
  'jesaja-bijbelquiz-deel-1',
  'jesaja-bijbelquiz-deel-10',
  'jesaja-bijbelquiz-deel-11',
  'jesaja-bijbelquiz-deel-12',
  'jesaja-bijbelquiz-deel-13',
  'jesaja-bijbelquiz-deel-14',
  'jesaja-bijbelquiz-deel-15',
  'jesaja-bijbelquiz-deel-16',
  'jesaja-bijbelquiz-deel-17',
  'jesaja-bijbelquiz-deel-18',
  'jesaja-bijbelquiz-deel-19',
  'jesaja-bijbelquiz-deel-2',
  'jesaja-bijbelquiz-deel-20',
  'jesaja-bijbelquiz-deel-21',
  'jesaja-bijbelquiz-deel-22',
  'jesaja-bijbelquiz-deel-23',
  'jesaja-bijbelquiz-deel-24',
  'jesaja-bijbelquiz-deel-25',
  'jesaja-bijbelquiz-deel-26',
  'jesaja-bijbelquiz-deel-27',
  'jesaja-bijbelquiz-deel-28',
  'jesaja-bijbelquiz-deel-29',
  'jesaja-bijbelquiz-deel-3',
  'jesaja-bijbelquiz-deel-30',
  'jesaja-bijbelquiz-deel-31',
  'jesaja-bijbelquiz-deel-32',
  'jesaja-bijbelquiz-deel-33',
  'jesaja-bijbelquiz-deel-34',
  'jesaja-bijbelquiz-deel-35',
  'jesaja-bijbelquiz-deel-36',
  'jesaja-bijbelquiz-deel-37',
  'jesaja-bijbelquiz-deel-38',
  'jesaja-bijbelquiz-deel-39',
  'jesaja-bijbelquiz-deel-4',
  'jesaja-bijbelquiz-deel-40',
  'jesaja-bijbelquiz-deel-5',
  'jesaja-bijbelquiz-deel-6',
  'jesaja-bijbelquiz-deel-7',
  'jesaja-bijbelquiz-deel-8',
  'jesaja-bijbelquiz-deel-9',
  'jona-bijbelquiz-deel-1',
  'jona-bijbelquiz-deel-2',
  'jona-bijbelquiz-deel-3',
  'jona-bijbelquiz-deel-4',
  'klaagliederen-bijbelquiz-deel-1',
  'klaagliederen-bijbelquiz-deel-2',
  'klaagliederen-bijbelquiz-deel-3',
  'klaagliederen-bijbelquiz-deel-4',
  'koningen-profeten-en-apostelen',
  'marcus-bijbelquiz-deel-1',
  'marcus-bijbelquiz-deel-10',
  'marcus-bijbelquiz-deel-11',
  'marcus-bijbelquiz-deel-12',
  'marcus-bijbelquiz-deel-13',
  'marcus-bijbelquiz-deel-14',
  'marcus-bijbelquiz-deel-15',
  'marcus-bijbelquiz-deel-16',
  'marcus-bijbelquiz-deel-2',
  'marcus-bijbelquiz-deel-3',
  'marcus-bijbelquiz-deel-4',
  'marcus-bijbelquiz-deel-5',
  'marcus-bijbelquiz-deel-6',
  'marcus-bijbelquiz-deel-7',
  'marcus-bijbelquiz-deel-8',
  'marcus-bijbelquiz-deel-9',
  'prediker',
  'ruth-bijbelquiz-deel-1',
  'ruth-bijbelquiz-deel-2',
  'ruth-bijbelquiz-deel-3',
  'ruth-bijbelquiz-deel-4',
  'wonderen-en-gebeurtenissen',
] as const;

export const QUIZ_COVER_SLUGS: ReadonlySet<string> = new Set(SLUGS);

/** The drawn cover for this slug, or null when none was rendered for it. */
export function coverForSlug(slug: string | null | undefined): string | null {
  if (!slug) return null;
  const key = slug.trim().toLowerCase();
  return QUIZ_COVER_SLUGS.has(key) ? `/images/quizzes/${key}.png` : null;
}
