#!/usr/bin/env node
/**
 * Expands `docs/quiz-image-prompts/manifest.json` into ready-to-paste image
 * prompts.
 *
 * WHY THIS EXISTS
 *
 * Nearly every quiz shares a cover with a few dozen others: a quiz without an
 * explicit `imageUrl` falls back to its *category* image, so all 45 New
 * Testament quizzes render img2.png and all 42 Old Testament quizzes render
 * img1.png. Fixing that means one artwork per quiz, and one artwork per quiz
 * means one prompt per quiz - written in exactly the style the existing
 * covers were generated in, or the grid stops looking like one product.
 *
 * The style lives in `docs/image-generation-prompt.txt` and is the single
 * source of truth. This script only substitutes `{SCENE_DESCRIPTION}` with the
 * per-quiz scene from the manifest, so a tweak to the house style is one edit
 * followed by one re-run, not 95 hand edits.
 *
 * OUTPUT
 *   docs/quiz-image-prompts/prompts/<slug>.txt   one prompt per quiz
 *   docs/quiz-image-prompts/all-prompts.md       every prompt in one file
 *
 * Generated images belong in `public/images/quizzes/<slug>.png`. After that,
 * run scripts/assign-quiz-images.mts to point the database at them.
 *
 * USAGE
 *   node --import tsx scripts/generate-quiz-image-prompts.mts
 */

import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

type ManifestQuiz = {
  slug: string;
  title: string;
  file: string;
  imageUrl: string;
  scene: string;
};

type Manifest = {
  template: string;
  targetDir: string;
  quizzes: ManifestQuiz[];
};

const root = process.cwd();
const manifestPath = path.join(root, 'docs/quiz-image-prompts/manifest.json');
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8')) as Manifest;
const template = fs.readFileSync(path.join(root, manifest.template), 'utf8').trim();

if (!template.includes('{SCENE_DESCRIPTION}')) {
  console.error(`${manifest.template} no longer contains {SCENE_DESCRIPTION} - nothing to substitute.`);
  process.exit(1);
}

const promptDir = path.join(root, 'docs/quiz-image-prompts/prompts');
fs.rmSync(promptDir, { recursive: true, force: true });
fs.mkdirSync(promptDir, { recursive: true });

const bundle: string[] = [
  '# Quiz cover prompts',
  '',
  `Generated by \`scripts/generate-quiz-image-prompts.mts\` from \`docs/quiz-image-prompts/manifest.json\`.`,
  `Style template: \`${manifest.template}\`. Save each result as \`${manifest.targetDir}/<slug>.png\`.`,
  '',
];

for (const quiz of manifest.quizzes) {
  const prompt = template.replace('{SCENE_DESCRIPTION}', quiz.scene);
  fs.writeFileSync(path.join(promptDir, `${quiz.slug}.txt`), `${prompt}\n`, 'utf8');
  bundle.push(`## ${quiz.title}`, '', `Save as: \`${manifest.targetDir}/${quiz.file}\``, '', '```', prompt, '```', '');
}

fs.writeFileSync(path.join(root, 'docs/quiz-image-prompts/all-prompts.md'), `${bundle.join('\n')}\n`, 'utf8');

console.log(`Wrote ${manifest.quizzes.length} prompts to docs/quiz-image-prompts/prompts/`);
console.log('Bundle: docs/quiz-image-prompts/all-prompts.md');
